project_id = "nroopuvfkooreoffwxsx"

[functions.legal-chat]
verify_jwt = false

[functions.process-document]
verify_jwt = true

[functions.scrape-website]
verify_jwt = false

[functions.analyze-document-ocr]
verify_jwt = false
